// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOMAC.EF;

namespace OOMAC.EF.Migrations
{
    [DbContext(typeof(OOMACDBContext))]
    [Migration("20220410152405_PoolsMergeIntoBrackets")]
    partial class PoolsMergeIntoBrackets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContestantTournament", b =>
                {
                    b.Property<int>("ContestansId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentsId")
                        .HasColumnType("int");

                    b.HasKey("ContestansId", "TournamentsId");

                    b.HasIndex("TournamentsId");

                    b.ToTable("ContestantTournament");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Bracket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BrcId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Round")
                        .HasColumnType("int")
                        .HasColumnName("BrcRound");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int")
                        .HasColumnName("BrcTrnId");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("BrcType");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Bracker");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Contestant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateBorn")
                        .HasColumnType("datetime2")
                        .HasColumnName("ConDateBorn");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConEmail");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConFName");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConLName");

                    b.Property<int>("TechSkill")
                        .HasColumnType("int")
                        .HasColumnName("ConTechnicalSkill");

                    b.HasKey("Id");

                    b.ToTable("Contestant");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BracketId")
                        .HasColumnType("int")
                        .HasColumnName("MatBrcIdId");

                    b.Property<int?>("ContestantAId")
                        .HasColumnType("int");

                    b.Property<int?>("ContestantBId")
                        .HasColumnType("int");

                    b.Property<int>("ContestantIdA")
                        .HasColumnType("int")
                        .HasColumnName("MatConIdAId");

                    b.Property<int>("ContestantIdB")
                        .HasColumnType("int")
                        .HasColumnName("MatConIdBId");

                    b.Property<string>("ScoreContestantAString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatScoreAId");

                    b.Property<string>("ScoreContestantBString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MatScoreBId");

                    b.HasKey("Id");

                    b.HasIndex("BracketId");

                    b.HasIndex("ContestantAId");

                    b.HasIndex("ContestantBId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TrnId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxAge")
                        .HasColumnType("int")
                        .HasColumnName("TrnMaxAge");

                    b.Property<int>("MaxTechnicalSkill")
                        .HasColumnType("int")
                        .HasColumnName("TrnMaxTechSkill");

                    b.Property<int>("MinAge")
                        .HasColumnType("int")
                        .HasColumnName("TrnMinAge");

                    b.Property<int>("MinTechnicalSkill")
                        .HasColumnType("int")
                        .HasColumnName("TrnMinTechSkill");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrnName");

                    b.HasKey("Id");

                    b.ToTable("Tournament");
                });

            modelBuilder.Entity("ContestantTournament", b =>
                {
                    b.HasOne("OOMAC.Domain.Models.Contestant", null)
                        .WithMany()
                        .HasForeignKey("ContestansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOMAC.Domain.Models.Tournament", null)
                        .WithMany()
                        .HasForeignKey("TournamentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Bracket", b =>
                {
                    b.HasOne("OOMAC.Domain.Models.Tournament", "Tournament")
                        .WithMany("Brackets")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Match", b =>
                {
                    b.HasOne("OOMAC.Domain.Models.Bracket", "Bracket")
                        .WithMany("Matches")
                        .HasForeignKey("BracketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OOMAC.Domain.Models.Contestant", "ContestantA")
                        .WithMany()
                        .HasForeignKey("ContestantAId");

                    b.HasOne("OOMAC.Domain.Models.Contestant", "ContestantB")
                        .WithMany()
                        .HasForeignKey("ContestantBId");

                    b.Navigation("Bracket");

                    b.Navigation("ContestantA");

                    b.Navigation("ContestantB");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Bracket", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("OOMAC.Domain.Models.Tournament", b =>
                {
                    b.Navigation("Brackets");
                });
#pragma warning restore 612, 618
        }
    }
}
